# Generated by Django 5.2.3 on 2025-06-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("estagios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="estagio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estagios.estagio"
            ),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="estagio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estagios.estagio"
            ),
        ),
    ]
