# Generated by Django 5.2.3 on 2025-06-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("lido", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("alerta", "Alerta"),
                            ("aviso", "Aviso"),
                        ],
                        default="geral",
                        max_length=50,
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contas.usuario"
                    ),
                ),
            ],
        ),
    ]
