# Generated by Django 5.2.4 on 2025-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Curso"),
                ),
                (
                    "inst",
                    models.CharField(
                        max_length=255, verbose_name="Instituição Ofertante"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(max_length=50, verbose_name="Nível do Curso"),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
    ]
