# Generated by Django 5.1.3 on 2025-09-08 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='instituicao.instituicao', verbose_name='Instituição Ofertante'),
        ),
    ]
