# Generated by Django 4.2.19 on 2025-09-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_alter_instituicao_responsaveis'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='inst',
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='instituicao.instituicao', verbose_name='Instituição Ofertante'),
        ),
    ]
