# Generated by Django 5.2.4 on 2025-08-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curso", "0001_initial"),
        ("instituicao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=255, verbose_name="Título da Vaga"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Vaga")),
                ("numVagas", models.IntegerField(verbose_name="Número de Vagas")),
                ("prazo", models.DateField(verbose_name="Prazo de Inscrição")),
                (
                    "cursos",
                    models.ManyToManyField(
                        related_name="vagas_relacionadas",
                        to="curso.curso",
                        verbose_name="Cursos Relacionados",
                    ),
                ),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="instituicao.instituicao",
                        verbose_name="Instituição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga",
                "verbose_name_plural": "Vagas",
            },
        ),
    ]
