# Generated by Django 5.2.4 on 2025-08-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuario", "0001_initial"),
        ("vaga", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_ini", models.DateField(verbose_name="Data de Início")),
                ("dt_fim", models.DateField(verbose_name="Data de Fim")),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Estágio Ativo"),
                ),
                (
                    "nota",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nota do Estágio"
                    ),
                ),
                (
                    "aluno",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estagio_realizado",
                        to="usuario.perfilusuario",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "orientador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estagios_orientados",
                        to="usuario.perfilusuario",
                        verbose_name="Orientador",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estagios_supervisionados",
                        to="usuario.perfilusuario",
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estagios_associados",
                        to="vaga.vaga",
                        verbose_name="Vaga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estágio",
                "verbose_name_plural": "Estágios",
            },
        ),
    ]
