# Generated by Django 5.1.3 on 2025-09-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ini', models.DateField(verbose_name='Data de Início')),
                ('dt_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.BooleanField(default=False, verbose_name='Estágio Ativo')),
                ('nota', models.FloatField(blank=True, null=True, verbose_name='Nota do Estágio')),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
            },
        ),
    ]
