# Generated by Django 5.1.3 on 2025-09-08 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagio', '0001_initial'),
        ('usuario', '0001_initial'),
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagio',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estagio_realizado', to='usuario.usuario', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_orientados', to='usuario.usuario', verbose_name='Orientador'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_supervisionados', to='usuario.usuario', verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='estagio',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios_associados', to='vaga.vaga', verbose_name='Vaga'),
        ),
    ]
