# Generated by Django 4.2.19 on 2025-09-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_remove_perfilusuario_curso_and_more'),
        ('estagio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='aluno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estagio_realizado', to='usuario.usuario', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_orientados', to='usuario.usuario', verbose_name='Orientador'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estagios_supervisionados', to='usuario.usuario', verbose_name='Supervisor'),
        ),
    ]
