# Generated by Django 5.2.4 on 2025-08-20 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_remove_perfilusuario_endereco_perfilusuario_bairro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfilusuario",
            name="foto_perfil",
        ),
    ]
