# Generated by Django 4.2.19 on 2025-09-06 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estagio', '0002_alter_estagio_aluno_alter_estagio_orientador_and_more'),
        ('usuario', '0004_usuario_remove_perfilusuario_curso_and_more'),
        ('curso', '0002_remove_curso_inst_curso_instituicao'),
        ('instituicao', '0005_alter_instituicao_responsaveis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='curso.curso', verbose_name='Curso'),
        ),
    ]
