# Generated by Django 5.2.4 on 2025-08-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instituicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Instituição"
                    ),
                ),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "status",
                    models.BooleanField(default=True, verbose_name="Status Ativo"),
                ),
                (
                    "responsaveis",
                    models.ManyToManyField(
                        related_name="instituicoes_responsavel",
                        to="usuario.perfilusuario",
                        verbose_name="Responsáveis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instituição",
                "verbose_name_plural": "Instituições",
            },
        ),
    ]
