# Generated by Django 5.1.3 on 2025-09-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('status', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('instituicao_ensino', 'Instituição de Ensino')], default='empresa', max_length=20, verbose_name='Tipo de Instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
    ]
