# Generated by Django 4.2.19 on 2025-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='tipo',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('instituicao_ensino', 'Instituição de Ensino')], default='empresa', max_length=20, verbose_name='Tipo de Instituição'),
        ),
    ]
