# Generated by Django 5.1.3 on 2025-09-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='instituicoes_responsavel', to='usuario.usuario', verbose_name='Responsáveis'),
        ),
    ]
