# Generated by Django 5.1.3 on 2025-08-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0002_instituicao_tipo'),
        ('usuario', '0003_remove_perfilusuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='instituicoes_responsavel', to='usuario.perfilusuario', verbose_name='Responsáveis'),
        ),
    ]
