# Generated by Django 4.2.19 on 2025-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0003_alter_instituicao_responsaveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituicao',
            name='endereco',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
