# Generated by Django 4.2.19 on 2025-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_remove_perfilusuario_curso_and_more'),
        ('instituicao', '0004_remove_instituicao_endereco_instituicao_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='instituicoes_responsavel', to='usuario.usuario', verbose_name='Responsáveis'),
        ),
    ]
