# Generated by Django 5.2.3 on 2025-06-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "instituicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.containstituicao",
                    ),
                ),
            ],
        ),
    ]
