# Generated by Django 5.2.3 on 2025-06-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0002_initial"),
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estagio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("carga_horaria", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contas.aluno"
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contas.professor",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contas.supervisor",
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vagas.vaga"
                    ),
                ),
            ],
        ),
    ]
