# Generated by Django 5.2.3 on 2025-06-20 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("aluno", "Aluno"),
                            ("empresa", "Empresa"),
                            ("professor", "Professor"),
                            ("supervisor", "Supervisor"),
                            ("instituicao", "Instituição"),
                        ],
                        default="aluno",
                        max_length=20,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contas.usuario",
                    ),
                ),
                ("matricula", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContaEmpresa",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contas.usuario",
                    ),
                ),
                ("nome_empresa", models.CharField(max_length=255)),
                (
                    "nivel_permissao",
                    models.CharField(
                        choices=[("basico", "Básico"), ("avancado", "Avançado")],
                        default="basico",
                        max_length=10,
                    ),
                ),
                ("localizacao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ContaInstituicao",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contas.usuario",
                    ),
                ),
                ("nome_instituicao", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contas.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="contas.usuario",
                    ),
                ),
                ("cargo", models.CharField(max_length=100)),
            ],
        ),
    ]
